# Generated by Django 4.2.7 on 2024-02-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_branch_alter_district_dname_person_branch_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('bname',), 'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('dname',), 'verbose_name': 'district', 'verbose_name_plural': 'districts'},
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
