# Generated by Django 4.2.7 on 2024-02-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_branch_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('phno', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=300)),
            ],
        ),
    ]
