# Generated by Django 4.2.7 on 2024-02-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_person_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name',), 'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name': 'district', 'verbose_name_plural': 'districts'},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='bname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='dname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.branch'),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.district'),
        ),
    ]
