# Generated by Django 4.2.7 on 2024-02-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0009_alter_person_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
    ]
